# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    desc "Generate new localized screenshots"
    lane :screenshots do
      capture_screenshots(scheme: "fastlaneSample")
      # - fastlane frameit
      frame_screenshots(white: true)
      # - use in Fastfile
      # upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
    end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "fastlaneSample")
    upload_to_testflight
  end
end
